name: fmt

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        node: [20]

    runs-on: ubuntu-24.04
    
    steps:
    - uses: actions/setup-node@v6
      with:
        node-version: ${{ matrix.node }}
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Please tell me who you are.
      run: |
          git config --global user.email "15198247+buyoh@users.noreply.github.com"
          git config --global user.name "buyoh(workflow)"
    - name: get git submodules
      run: |
        git submodule init
        git submodule update
    - name: install packages
      run: |
        npm ci
    - name: lint javascript
      run: |
        npm run lint-fix
    - name: commit phase
      run: |
        if [ `git diff | wc -l` -ne 0 ] ; then
        echo detect diff
        git add .
        git commit -m 'lint-fix by Github Actions'
        fi
    - uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}